// scaler.h — GENERATED by training/train.py on 2026-09-23 02:22 UTC. Do not edit by hand.
// StandardScaler constants in features.h order:
//   ph, tds, turbidity, temperature, color_r, color_g, color_b, color_clear
#pragma once

#include <features.h>

static const float FEAT_MEAN[FEATURE_COUNT] = {
  1589.75f, 1968.66f, 284.0f, 22.9622f, 57.4706f, 58.0392f,
  48.8039f, 93.2941f
};

static const float FEAT_SCALE[FEATURE_COUNT] = {
  751.121f, 537.579f, 1.0f, 2.24334f, 61.333f, 63.5594f,
  61.849f, 98.7515f
};

// Recommended "Uncertain" cut-off from the threshold sweep. Adjustable in Settings.
static const float CONF_THRESHOLD = 0.40f;
