// scaler.h — GENERATED by training/train.py on 2026-08-17 08:24 UTC. Do not edit by hand.
// StandardScaler constants in features.h order:
//   ph, tds, turbidity, density, temperature, color_r, color_g, color_b, color_clear
#pragma once

#include <features.h>

static const float FEAT_MEAN[FEATURE_COUNT] = {
  1526.27f, 677.258f, 1220.06f, 1.0297f, 25.7f, 869.694f,
  844.472f, 761.861f, 2608.67f
};

static const float FEAT_SCALE[FEATURE_COUNT] = {
  102.427f, 149.856f, 211.34f, 0.00812076f, 2.21585f, 65.3503f,
  55.5475f, 44.8783f, 265.451f
};

// Recommended "Uncertain" cut-off from the threshold sweep. Adjustable in Settings.
static const float CONF_THRESHOLD = 0.40f;
