#!/usr/bin/env python3
"""Gzip 03_deployment/dashboard.html into 03_deployment/dashboard.h (PROGMEM byte array).

The ESP32 serves the dashboard straight from flash with Content-Encoding: gzip, so the
page never costs RAM and stays well under the flash budget. Run this after editing
dashboard.html; CI runs it before every firmware build, so the committed header can
never drift from the HTML.

    python tools/build_dashboard.py
"""
import gzip
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "03_deployment" / "dashboard.html"
DST = ROOT / "03_deployment" / "dashboard.h"


def main() -> int:
    if not SRC.exists():
        print(f"error: {SRC} not found", file=sys.stderr)
        return 1

    raw = SRC.read_bytes()
    # mtime=0 keeps the output byte-identical for identical input, so rebuilds do not
    # show up as spurious diffs.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = [
        "// dashboard.h — GENERATED by tools/build_dashboard.py. Do not edit.",
        "// Source: 03_deployment/dashboard.html",
        f"// {len(raw)} bytes of HTML -> {len(packed)} bytes gzipped.",
        "#pragma once",
        "",
        f"static const size_t DASHBOARD_HTML_GZ_LEN = {len(packed)};",
        "static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(packed), 16):
        chunk = packed[i : i + 16]
        lines.append("  " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    DST.write_text("\n".join(lines) + "\n", encoding="utf-8")

    ratio = 100 * len(packed) / len(raw) if raw else 0
    print(f"{SRC.name}: {len(raw)} B -> {len(packed)} B gzipped ({ratio:.0f}%) -> {DST.name}")
    if len(packed) > 60_000:
        print("warning: dashboard is getting large for PROGMEM; keep it lean", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
